FROM eclipse-temurin:21-jdk
ENV TZ=Europe/Warsaw

COPY ./files/*.jar ./app.jar
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.18.0/opentelemetry-javaagent.jar /opt/opentelemetry-agent.jar
#
# ENTRYPOINT java -javaagent:/opt/opentelemetry-agent.jar \
#     -Dotel.resource.attributes=service.instance.id=$HOSTNAME \
#     -jar /app.jar

ENTRYPOINT ["java","-jar", "./app.jar"]
